#!/bin/bash

DEBOUNCE=5 # number of seconds after last file change to start building

# Stop script as soon as any command returns error
# set -e

echo "Checking for myst to be installed"

# Check if myst is installed
if ! command -v myst &> /dev/null; then
    echo "Error: myst is not installed. Wait minute, the devcontainer might not be ready yet." >&2
    exit 1
fi

echo "Starting new http-server..."

# Kill http-server if it is running
pkill -f "http-server" 2>/dev/null || true

# Wait untill port 8080 is available
while lsof -i :8080 >/dev/null 2>&1; do
    sleep 0.2
done

# Starting http-server for static-html files generated by MyST
npx -y http-server _build/html -c-1 &

# Rebuild site after each file change, including debounce
echo "Watching files (ignoring hidden and _ folders)..."

while true; do

    echo "Building html..."
    
    # kill process on port 3000
    fuser -k 3000/tcp
    # Wait untill port 3000 is available
    while lsof -i :3000 >/dev/null 2>&1; do
        sleep 0.2
    done

    # kill process on port 3100
    fuser -k 3100/tcp
    # Wait untill port 3100 is available
    while lsof -i :3100 >/dev/null 2>&1; do
        sleep 0.2
    done

    # build new html files
    myst build --html

    echo "Waiting for changes..."

    # wait for change 
    inotifywait -r -e close_write --exclude '(/\.|/_).*' . --quiet --format '%w%f'

    # wait untill there are no more changes for 10 seconds
    while inotifywait -r -e close_write --exclude '(/\.|/_).*' . --quiet --format '%w%f' -t $DEBOUNCE; do
        :
    done

done